const emoji = {
  path: "https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/",
  list: [
    { url: "0.gif", alt: "[微笑]" },
    { url: "1.gif", alt: "[撇嘴]" },
    { url: "2.gif", alt: "[色]" },
    { url: "3.gif", alt: "[发呆]" },
    { url: "4.gif", alt: "[得意]" },
    { url: "5.gif", alt: "[流泪]" },
    { url: "6.gif", alt: "[害羞]" },
    { url: "7.gif", alt: "[闭嘴]" },
    { url: "8.gif", alt: "[睡]" },
    { url: "9.gif", alt: "[大哭]" },
    { url: "10.gif", alt: "[尴尬]" },
    { url: "11.gif", alt: "[发怒]" },
    { url: "12.gif", alt: "[调皮]" },
    { url: "13.gif", alt: "[呲牙]" },
    { url: "14.gif", alt: "[惊讶]" },
    { url: "15.gif", alt: "[难过]" },
    { url: "16.gif", alt: "[酷]" },
    { url: "17.gif", alt: "[冷汗]" },
    { url: "18.gif", alt: "[抓狂]" },
    { url: "19.gif", alt: "[吐]" },
    { url: "20.gif", alt: "[偷笑]" },
    { url: "21.gif", alt: "[可爱]" },
    { url: "22.gif", alt: "[白眼]" },
    { url: "23.gif", alt: "[傲慢]" },
    { url: "24.gif", alt: "[饥饿]" },
    { url: "25.gif", alt: "[困]" },
    { url: "26.gif", alt: "[惊恐]" },
    { url: "27.gif", alt: "[流汗]" },
    { url: "28.gif", alt: "[憨笑]" },
    { url: "29.gif", alt: "[大兵]" },
    { url: "30.gif", alt: "[奋斗]" },
    { url: "31.gif", alt: "[咒骂]" },
    { url: "32.gif", alt: "[疑问]" },
    { url: "33.gif", alt: "[嘘]" },
    { url: "34.gif", alt: "[晕]" },
    { url: "35.gif", alt: "[折磨]" },
    { url: "36.gif", alt: "[衰]" },
    { url: "37.gif", alt: "[骷髅]" },
    { url: "38.gif", alt: "[敲打]" },
    { url: "39.gif", alt: "[再见]" },
    { url: "40.gif", alt: "[擦汗]" },
    { url: "41.gif", alt: "[抠鼻]" },
    { url: "42.gif", alt: "[鼓掌]" },
    { url: "43.gif", alt: "[糗大了]" },
    { url: "44.gif", alt: "[坏笑]" },
    { url: "45.gif", alt: "[左哼哼]" },
    { url: "46.gif", alt: "[右哼哼]" },
    { url: "47.gif", alt: "[哈欠]" },
    { url: "48.gif", alt: "[鄙视]" },
    { url: "49.gif", alt: "[委屈]" },
    { url: "50.gif", alt: "[快哭了]" },
    { url: "51.gif", alt: "[阴险]" },
    { url: "52.gif", alt: "[亲亲]" },
    { url: "53.gif", alt: "[吓]" },
    { url: "54.gif", alt: "[可怜]" },
    { url: "55.gif", alt: "[菜刀]" },
    { url: "56.gif", alt: "[西瓜]" },
    { url: "57.gif", alt: "[啤酒]" },
    { url: "58.gif", alt: "[篮球]" },
    { url: "59.gif", alt: "[乒乓]" },
    { url: "60.gif", alt: "[咖啡]" },
    { url: "61.gif", alt: "[饭]" },
    { url: "62.gif", alt: "[猪头]" },
    { url: "63.gif", alt: "[玫瑰]" },
    { url: "64.gif", alt: "[凋谢]" },
    { url: "65.gif", alt: "[示爱]" },
    { url: "66.gif", alt: "[爱心]" },
    { url: "67.gif", alt: "[心碎]" },
    { url: "68.gif", alt: "[蛋糕]" },
    { url: "69.gif", alt: "[闪电]" },
    { url: "70.gif", alt: "[炸弹]" },
    { url: "71.gif", alt: "[刀]" },
    { url: "72.gif", alt: "[足球]" },
    { url: "73.gif", alt: "[瓢虫]" },
    { url: "74.gif", alt: "[便便]" },
    { url: "75.gif", alt: "[月亮]" },
    { url: "76.gif", alt: "[太阳]" },
    { url: "77.gif", alt: "[礼物]" },
    { url: "78.gif", alt: "[拥抱]" },
    { url: "79.gif", alt: "[强]" },
    { url: "80.gif", alt: "[弱]" },
    { url: "81.gif", alt: "[握手]" },
    { url: "82.gif", alt: "[胜利]" },
    { url: "83.gif", alt: "[抱拳]" },
    { url: "84.gif", alt: "[勾引]" },
    { url: "85.gif", alt: "[拳头]" },
    { url: "86.gif", alt: "[差劲]" },
    { url: "87.gif", alt: "[爱你]" },
    { url: "88.gif", alt: "[NO]" },
    { url: "89.gif", alt: "[OK]" },
    { url: "90.gif", alt: "[爱情]" },
    { url: "91.gif", alt: "[飞吻]" },
    { url: "92.gif", alt: "[跳跳]" },
    { url: "93.gif", alt: "[发抖]" },
    { url: "94.gif", alt: "[怄火]" },
    { url: "95.gif", alt: "[转圈]" },
    { url: "96.gif", alt: "[磕头]" },
    { url: "97.gif", alt: "[回头]" },
    { url: "98.gif", alt: "[跳绳]" },
    { url: "99.gif", alt: "[挥手]" },
    { url: "100.gif", alt: "[激动]" },
    { url: "101.gif", alt: "[街舞]" },
    { url: "102.gif", alt: "[献吻]" },
    { url: "103.gif", alt: "[左太极]" },
    { url: "104.gif", alt: "[右太极]" },
  ],
};
export default emoji;
export const emoji2 = {
  path: "https://lf3-cdn-tos.bytescm.com/obj/static/xitu_juejin_web/img/",
  list: [
    { url: "jj_emoji_1.7d9f699.png", alt: "[微笑]" },
    { url: "jj_emoji_2.cd1e2bd.png", alt: "[呲牙]" },
    { url: "jj_emoji_3.41d9a9a.png", alt: "[色]" },
    { url: "jj_emoji_4.28b310a.png", alt: "[发呆]" },
    { url: "jj_emoji_5.ece2a96.png", alt: "[可怜]" },
    { url: "jj_emoji_6.dde0d83.png", alt: "[流泪]" },
    { url: "jj_emoji_7.eca1535.png", alt: "[害羞]" },
    { url: "jj_emoji_8.c6ea514.png", alt: "[闭嘴]" },
    { url: "jj_emoji_9.8cf4c38.png", alt: "[睡]" },
    { url: "jj_emoji_10.42a731c.png", alt: "[吃瓜群众]" },
    { url: "jj_emoji_11.8824107.png", alt: "[尴尬]" },
    { url: "jj_emoji_12.0f24f23.png", alt: "[发怒]" },
    { url: "jj_emoji_13.aaa8265.png", alt: "[调皮]" },
    { url: "jj_emoji_14.8130d96.png", alt: "[撇嘴]" },
    { url: "jj_emoji_15.f58c082.png", alt: "[思考]" },
    { url: "jj_emoji_16.9d17f6d.png", alt: "[不失礼貌的微笑]" },
    { url: "jj_emoji_17.bcebf79.png", alt: "[奸笑]" },
    { url: "jj_emoji_18.b93331d.png", alt: "[抓狂]" },
    { url: "jj_emoji_19.249e025.png", alt: "[吐]" },
    { url: "jj_emoji_20.7a46372.png", alt: "[偷笑]" },
    { url: "jj_emoji_21.c408154.png", alt: "[愉快]" },
    { url: "jj_emoji_22.281d379.png", alt: "[白眼]" },
    { url: "jj_emoji_23.27eb25d.png", alt: "[傲慢]" },
    { url: "jj_emoji_24.6e6570b.png", alt: "[困]" },
    { url: "jj_emoji_25.51e6984.png", alt: "[灵光一现]" },
    { url: "jj_emoji_26.1117a72.png", alt: "[流汗]" },
    { url: "jj_emoji_27.0006230.png", alt: "[憨笑]" },
    { url: "jj_emoji_28.8981538.png", alt: "[捂脸]" },
    { url: "jj_emoji_29.2801857.png", alt: "[奋斗]" },
    { url: "jj_emoji_30.91e4aa4.png", alt: "[咒骂]" },
    { url: "jj_emoji_31.606e7a5.png", alt: "[疑问]" },
    { url: "jj_emoji_32.0de65f2.png", alt: "[嘘]" },
    { url: "jj_emoji_33.12a8e53.png", alt: "[晕]" },
    { url: "jj_emoji_34.cf5b4d5.png", alt: "[衰]" },
    { url: "jj_emoji_35.8d57f28.png", alt: "[骷髅]" },
    { url: "jj_emoji_36.c31c83f.png", alt: "[敲打]" },
    { url: "jj_emoji_37.2f6e44f.png", alt: "[再见]" },
    { url: "jj_emoji_38.2d77d3e.png", alt: "[擦汗]" },
    { url: "jj_emoji_39.5b41924.png", alt: "[抠鼻]" },
    { url: "jj_emoji_40.348108b.png", alt: "[泣不成声]" },
    { url: "jj_emoji_41.2751fc1.png", alt: "[坏笑]" },
    { url: "jj_emoji_42.886fc7b.png", alt: "[左哼哼]" },
    { url: "jj_emoji_43.ab03a70.png", alt: "[右哼哼]" },
    { url: "jj_emoji_44.74cc36f.png", alt: "[打哈欠]" },
    { url: "jj_emoji_45.df24295.png", alt: "[鄙视]" },
    { url: "jj_emoji_46.82c0215.png", alt: "[委屈]" },
    { url: "jj_emoji_47.63391a1.png", alt: "[快哭了]" },
    { url: "jj_emoji_48.1b40529.png", alt: "[摸头]" },
    { url: "jj_emoji_49.392c709.png", alt: "[阴险]" },
    { url: "jj_emoji_50.419e678.png", alt: "[亲亲]" },
    { url: "jj_emoji_51.e6d838e.png", alt: "[机智]" },
    { url: "jj_emoji_52.cc6d6bc.png", alt: "[得意]" },
    { url: "jj_emoji_53.3e59e29.png", alt: "[大金牙]" },
    { url: "jj_emoji_54.08f068d.png", alt: "[拥抱]" },
    { url: "jj_emoji_55.74ed629.png", alt: "[大笑]" },
    { url: "jj_emoji_56.5777828.png", alt: "[送心]" },
    { url: "jj_emoji_57.6b8baad.png", alt: "[震惊]" },
    { url: "jj_emoji_58.327784e.png", alt: "[酷拽]" },
    { url: "jj_emoji_59.8a63cb5.png", alt: "[尬笑]" },
    { url: "jj_emoji_60.9016267.png", alt: "[大哭]" },
    { url: "jj_emoji_61.a296509.png", alt: "[哭笑]" },
    { url: "jj_emoji_62.d7ca811.png", alt: "[做鬼脸]" },
    { url: "jj_emoji_63.c32f5b5.png", alt: "[红脸]" },
    { url: "jj_emoji_64.6c4f6bb.png", alt: "[鼓掌]" },
    { url: "jj_emoji_65.19740fe.png", alt: "[恐惧]" },
    { url: "jj_emoji_66.fb6750b.png", alt: "[斜眼]" },
    { url: "jj_emoji_67.9ceed33.png", alt: "[嘿哈]" },
    { url: "jj_emoji_68.1e326db.png", alt: "[惊讶]" },
    { url: "jj_emoji_69.cabd864.png", alt: "[绝望的凝视]" },
    { url: "jj_emoji_70.285ebe9.png", alt: "[囧]" },
    { url: "jj_emoji_71.e8c2090.png", alt: "[皱眉]" },
    { url: "jj_emoji_72.04f3881.png", alt: "[耶]" },
    { url: "jj_emoji_73.55516c0.png", alt: "[石化]" },
    { url: "jj_emoji_74.d954f2d.png", alt: "[我想静静]" },
    { url: "jj_emoji_75.b7ccb48.png", alt: "[吐血]" },
    { url: "jj_emoji_76.8452494.png", alt: "[互粉]" },
    { url: "jj_emoji_77.afd454e.png", alt: "[互相关注]" },
    { url: "jj_emoji_78.28310a5.png", alt: "[加好友]" },
    { url: "jj_emoji_79.6185c09.png", alt: "[强]" },
    { url: "jj_emoji_80.d0a73bb.png", alt: "[钱]" },
    { url: "jj_emoji_81.8e1cf74.png", alt: "[飞吻]" },
    { url: "jj_emoji_82.c6f2aee.png", alt: "[打脸]" },
    { url: "jj_emoji_83.bc66012.png", alt: "[惊恐]" },
    { url: "jj_emoji_84.10dda08.png", alt: "[悠闲]" },
    { url: "jj_emoji_85.43ad2fc.png", alt: "[泪奔]" },
    { url: "jj_emoji_86.8b2a629.png", alt: "[舔屏]" },
    { url: "jj_emoji_87.f741137.png", alt: "[紫薇别走]" },
    { url: "jj_emoji_88.4eb52e4.png", alt: "[听歌]" },
    { url: "jj_emoji_89.5a2cba8.png", alt: "[难过]" },
    { url: "jj_emoji_90.aa0a4e8.png", alt: "[生病]" },
    { url: "jj_emoji_91.57fc147.png", alt: "[绿帽子]" },
    { url: "jj_emoji_92.13db022.png", alt: "[如花]" },
    { url: "jj_emoji_93.5ee641b.png", alt: "[惊喜]" },
    { url: "jj_emoji_94.f9c84dc.png", alt: "[吐彩虹]" },
    { url: "jj_emoji_95.6b0752f.png", alt: "[吐舌]" },
    { url: "jj_emoji_96.4fb9d71.png", alt: "[无辜呆]" },
    { url: "jj_emoji_97.39cdc9f.png", alt: "[看]" },
    { url: "jj_emoji_98.9f6d4ad.png", alt: "[白眼的狗]" },
    { url: "jj_emoji_99.3264111.png", alt: "[黑脸]" },
    { url: "jj_emoji_100.6adf5c8.png", alt: "[猪头]" },
    { url: "jj_emoji_101.dec591d.png", alt: "[熊吉]" },
    { url: "jj_emoji_102.b113c42.png", alt: "[不看]" },
    { url: "jj_emoji_103.6c2eed8.png", alt: "[玫瑰]" },
    { url: "jj_emoji_104.680e2d1.png", alt: "[凋谢]" },
    { url: "jj_emoji_105.3881f71.png", alt: "[嘴唇]" },
    { url: "jj_emoji_106.ba42c9a.png", alt: "[爱心]" },
    { url: "jj_emoji_107.1c0b941.png", alt: "[心碎]" },
    { url: "jj_emoji_108.a6defc6.png", alt: "[赞]" },
    { url: "jj_emoji_109.7854933.png", alt: "[弱]" },
    { url: "jj_emoji_110.34d5723.png", alt: "[握手]" },
    { url: "jj_emoji_111.b8dc9e6.png", alt: "[ok]" },
    { url: "jj_emoji_112.2dd347d.png", alt: "[谢谢]" },
    { url: "jj_emoji_113.582f64b.png", alt: "[比心]" },
    { url: "jj_emoji_114.4b8db8b.png", alt: "[碰拳]" },
    { url: "jj_emoji_115.a7dbbf7.png", alt: "[击掌]" },
    { url: "jj_emoji_116.16df22c.png", alt: "[左]" },
    { url: "jj_emoji_117.6dd2889.png", alt: "[右]" },
    { url: "jj_emoji_118.1612154.png", alt: "[力量]" },
    { url: "jj_emoji_119.947368f.png", alt: "[胜利]" },
    { url: "jj_emoji_120.6c3effe.png", alt: "[抱拳]" },
    { url: "jj_emoji_121.570cd4d.png", alt: "[勾引]" },
    { url: "jj_emoji_122.b3763ee.png", alt: "[拳头]" },
    { url: "jj_emoji_123.da47506.png", alt: "[庆祝]" },
    { url: "jj_emoji_124.83c188d.png", alt: "[礼物]" },
    { url: "jj_emoji_125.ac32796.png", alt: "[红包]" },
    { url: "jj_emoji_126.21e6944.png", alt: "[禁]" },
    { url: "jj_emoji_127.ce1b9d7.png", alt: "[去污粉]" },
    { url: "jj_emoji_128.e55728c.png", alt: "[666]" },
    { url: "jj_emoji_129.0b59244.png", alt: "[给力]" },
    { url: "jj_emoji_130.2e42cc3.png", alt: "[v5]" },
    { url: "jj_emoji_131.e225098.png", alt: "[菜刀]" },
    { url: "jj_emoji_132.fe320d4.png", alt: "[炸弹]" },
    { url: "jj_emoji_133.2665597.png", alt: "[便便]" },
    { url: "jj_emoji_134.a4856c6.png", alt: "[月亮]" },
    { url: "jj_emoji_135.5741bcc.png", alt: "[太阳]" },
    { url: "jj_emoji_136.5eba004.png", alt: "[发]" },
    { url: "jj_emoji_137.9dd21f9.png", alt: "[黄瓜]" },
    { url: "jj_emoji_138.b0effa7.png", alt: "[西瓜]" },
    { url: "jj_emoji_139.ccb84eb.png", alt: "[啤酒]" },
    { url: "jj_emoji_140.6908619.png", alt: "[咖啡]" },
    { url: "jj_emoji_141.7bc6b3d.png", alt: "[蛋糕]" },
  ],
};
//将emoji图片转文字
export const parseEmojiToText = (str) => {
  // str='<img src="/images/1.gif" alt="[微笑]">你好<img src="/images/2.gif" alt="[伤心]">'
  console.log(str)
  let imgReg = /<img[^>]*src[=\'\"\s]+([^\"\']*)[\"\']?[^>]*>/gi;

  return str.replaceAll(imgReg, function (item, index) {
    
   let  altMatch = item.match(/alt="(.+?)"/);
   
    return altMatch[1];
  });
};
//替换表情符号文字为图片
export const replaceTextToEmoji = (str) => {
	// console.log(typeof str)
  let replacedStr = str.replace(/\[([^(\]|\[)]*)\]/g, (item, index) => {
    // console.log("item: " + item);
    for (let i = 0; i < emoji2.list.length; i++) {
      let row = emoji2.list[i];
      if (row.alt == item) {
        let imgstr = `<img src="${
          emoji2.path + row.url
        }" alt="${item}" style="margin:0 2px; vertical-align:text-bottom;
        width: 24px;
        height: 24px;">`;
        return imgstr;
      }
    }
  });
  replacedStr=replacedStr.replace(/\#([^\#|.]+)\#/g, (item, index) => {
  	return `<span style="color:#007AFF;margin-right: 5px;">${item}</span>`
  })
  return replacedStr;
};
